#!/bin/bash

# Call this command on your server to install OT Node Check (otcheck):
# curl -s https://raw.githubusercontent.com/befranz/otcheck/master/install-otcheck|bash&&source $HOME/.profile

VERSION="1.0"
WHOAMI=$(whoami)
OS=$(lsb_release -is)
SCRIPTSPATH="$HOME/scripts"

if [ "$WHOAMI" = "root" ]; then
  if [[ "$OS" == "Ubuntu" || "$OS" == "Debian" ]]; then
    mkdir -p $SCRIPTSPATH
    # Install jq and bc
    apt -y install jq bc >/dev/null 2>&1
    curl -s 'https://raw.githubusercontent.com/befranz/otcheck/master/otcheck'\
         -o $SCRIPTSPATH/otcheck
    CURLRC=$?
    if [ "$CURLRC" = "0" ]; then
      chmod +x $SCRIPTSPATH/otcheck
      cp -n $HOME/.profile $HOME/.profile.bak
      grep -q "$SCRIPTSPATH" $HOME/.profile || echo "export PATH=\$PATH:$SCRIPTSPATH" >> $HOME/.profile
      echo
      echo 'Installation of OT Node Check successful! Just type "otcheck" to start it.'
      echo
      exit 0
    else
      echo
      echo "Something went wrong with the installation! Check https://befranz.net/otnode/otcheck"
      echo
      exit 1
    fi
  else
    echo
    echo "Only Ubuntu and Debian are supported! Installation failed."
    echo
    exit 1
  fi
else
  echo
  echo "Only user root can run OT Node Check! Installation failed."
  echo
  exit 1
fi
